Merged PR 1427: Implement Semantic Versioning templates
Implements the necessary pieces for semantic versioning utilizing `launch-cli`'s versioning commands to provide automated version bumps based on the source branch name associated with a pull request.

For more info on Semantic Versioning, see here: https://semver.org/

Changes will need to be made to individual repos' ci.yaml and cd.yaml pipeline definitions, which will be covered with separate PRs for each repo. Once implemented on a repo, contributors must prefix branches as follows:
|Prefix|Outcome|
|---|---|
|`fix/*`, `patch/*`, `bug/*` | PATCH version increase|
|`feature/*` | MINOR version increase|
|`fix!/*`, `patch!/*`, `bug!/*`, `feature!/*` | MAJOR version increase|

Any other prefix or format will result in the PR failing to pass checks.

Related work items: #4070

diff --git a/applications/steps/local-build-and-push-docker-image.yaml b/applications/steps/local-build-and-push-docker-image.yaml
--- a/applications/steps/local-build-and-push-docker-image.yaml
+++ b/applications/steps/local-build-and-push-docker-image.yaml
@@ -25,6 +25,23 @@ parameters:
     default: 'Dockerfile'
 
 steps:
+  - task: AzureClI@2
+    name: CreateCommaSeparatedTagList
+    displayName: Create comma-separated tag list
+    inputs:
+      scriptType: bash
+      scriptLocation: inlineScript
+      workingDirectory: $(System.DefaultWorkingDirectory)
+      inlineScript: |
+        # Takes whatever was supplied in the parameter, turns newlines into commas, 
+        # and drops leading and trailing commas that may arise from blank newlines
+        COMMA_SEPARATED_TAGS=$(echo "${{ parameters.dockerImageTag }}" | paste -s -d, - | sed -E 's/^,*(.*[^,]),*$/\1/gi')
+        echo "COMMA_SEPARATED_TAGS=$COMMA_SEPARATED_TAGS"
+        [ -n "$COMMA_SEPARATED_TAGS" ] || (echo "No tag could be parsed for this repository. Cannot continue!" ; exit 1)
+        echo "##vso[task.setvariable variable=CommaSeparatedTagList;isOutput=true]$COMMA_SEPARATED_TAGS"
+      azureSubscription: ${{ parameters.serviceConnection }}
+      addSpnToEnvironment: true
+
   - task: AzureCLI@2
     displayName: 'Login to container registry'
     inputs:
@@ -46,7 +63,7 @@ steps:
       command: build
       Dockerfile: ${{ parameters.dockerfile }}
       arguments: --build-arg FEED_ACCESSTOKEN=$(System.Accesstoken)
-      tags: ${{ parameters.dockerImageTag }}
+      tags: $(CreateCommaSeparatedTagList.CommaSeparatedTagList)
 
   - task: AzureCLI@2
     displayName: 'Push image to repo'
